### PR TITLE
[test_0]: HelloWorld PR for Day0.

### PR DESCRIPTION
**Pull request by Rogerlv51**
### What?
- brief：这是一个测试pr，第0天
- author：Roger_lv（微信昵称）

### Directory Specification
暂无，just for test
### What changes are included in this PR?
包含了一个团队目录、个人目录、个人学习内容（src文件夹下创建main.cpp程序-just a hello world）

### Are these changes tested?
测试代码见个人目录-src目录下main.cpp，这是一个简单的hello world测试程序，还有一个README测试说明

### other information
None

### CODE REVIEW

**Comment by Light-City** [comment]
> ### What?
> * **brief：这是一个测试pr，第0天**
> * **author：Roger_lv（微信昵称）**
> 
> ### What changes are included in this PR?
> **包含了一个团队目录、个人目录、个人学习内容（src文件夹下创建main.cpp程序-just a hello world）**
> 
> ### Are these changes tested?
> **测试代码见个人目录-src目录下main.cpp，这是一个简单的hello world测试程序，还有一个README测试说明**

Please pay attention to the format of PR content, adopt the template format when submitting PR

**Comment by Light-City** [comment]
The directory structure is incorrect, you can refer to what others have done, or this document
> https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

**Comment by Rogerlv51** [comment]
I just updated, thank u.

**Comment by Rogerlv51** [comment]
> The directory structure is incorrect, you can refer to what others have done, or this document
> 
> > https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

I just updated, thank u.

**Comment by Light-City** [comment]
dir should follow lowcase underscore style ,such as: Roger_lv -> roger_lv

**Comment by Rogerlv51** [comment]
> dir should follow lowcase underscore style ,such as: Roger_lv -> roger_lv

My fault, sorry. Already done, thanks.

**Comment by Light-City** [comment]
LGTM, fighting!

**Pull request closed without merging**
