### PR TITLE
[daydayup_addteam_1]: apply to create a team directory.

### PR DESCRIPTION
**Pull request by xuehuasu**
### What?

- brief: 创建了小组目录
- author: xuehuasu

### What changes are included in this PR?

组名叫daydayup
组员分别是xuehuasu ， ivarn-d ，tigerwe

### Directory Specification
```
└── stl -> root dir
    ├── README.md 
    ├── example
    │   ├── README.md
    │   └── week1.cpp
    ├─daydayup -> our team name
    │  ├─ivarn-d  -> our team member 1
    │  │  └─src    
    |    |   └─test.md   
    │  ├─tigerwe -> our team member 2
    │  │  └─src   
    |    |   └─test.md   
    │  └─xuehuasu-> our team member 3
    │      └─src    
    |       └─test.md   
```

### CODE REVIEW

**Comment by XavierZXY** [comment]
- 请按照PR规范提交，[Team_Task]: Your Custom Title.

**Comment by XavierZXY** [comment]
> ### Are these changes tested?
> 目录长这样：

- 建议修改为 Directory Specification

**Comment by xuehuasu** [comment]
> 

是这样的吗

**Comment by XavierZXY** [comment]
- 目录参考格式
```
└── stl -> root dir
    ├── README.md 
    ├── example
    │   ├── README.md
    │   └── week1.cpp
    ├── fight_flow  -> your team name should follow lowercase underscore style(小写下划线)
    │   ├── lisi -> team member name1, please use english name
    │   │   └── learning.md -> your document file
    │   │   └── src -> your source code
    │   └── zhangsan -> team member name2
    │       └── vector.md -> your document file
    │       └── src -> your source code
```

**Comment by xuehuasu** [comment]
> * 目录参考格式
> 
> ```
> └── stl -> root dir
>     ├── README.md 
>     ├── example
>     │   ├── README.md
>     │   └── week1.cpp
>     ├── fight_flow  -> your team name should follow lowercase underscore style(小写下划线)
>     │   ├── lisi -> team member name1, please use english name
>     │   │   └── learning.md -> your document file
>     │   │   └── src -> your source code
>     │   └── zhangsan -> team member name2
>     │       └── vector.md -> your document file
>     │       └── src -> your source code
> ```

原来不能贴图片的吗，已经改好了，辛苦大佬再检查一下

**Comment by XavierZXY** [comment]
- 帮你改了标题和目录格式，记得开一下

**Comment by XavierZXY** [comment]
LGTM

**Comment by xuehuasu** [comment]
> * 帮你改了标题和目录格式，记得看一下

看到了看到了，谢谢大佬

**Comment by Light-City** [comment]
please see ci/cd code format.

**Comment by xuehuasu** [comment]
> please see ci/cd code format.

After experiencing so many mistakes, I think there is no problem now.

**Pull request merged**
