### PR TITLE
[mick_0]: Hello world pr

### PR DESCRIPTION
**Pull request by wwb1942**
Feature: pr test

Hello world test.

Author: mickwang1942@outlook.com

### What changes are included in this PR?

Add hello world.cpp

### CODE REVIEW

**Comment by Light-City** [comment]
Team_Mick -> team_mick 

lowercase undercase style.

**Comment by Light-City** [comment]
The directory structure is incorrect, you can refer to what others have done, or this document

https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

**Comment by wwb1942** [comment]
> The directory structure is incorrect, you can refer to what others have done, or this document
> 
> https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

Thx, I have changed dir and renamed folder name.

**Comment by Light-City** [comment]
LGTM

**Pull request closed without merging**
