### PR TITLE
[test_lyn_0]: first helloworld pr.

### PR DESCRIPTION
**Pull request by Babylonehy**
### What?

- brief: add helloworld and create floders
- author: lixiangwhuerhy@gmail.com

### What changes are included in this PR?

add `hello.cpp` to `stl/test/lyn/src`.

### Are these changes tested?

image

### CODE REVIEW

**Comment by Light-City** [comment]
1.The directory structure is incorrect, you can refer to what others have done, or this document

https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

2. follow google style, such as:

```
int main() {

}
```

**Comment by Light-City** [comment]
you pr title istyle is wrong

**Comment by Babylonehy** [comment]
> you pr title istyle is wrong

tks, I have fixed the sytle and structure. Is that correct?

**Comment by martinx** [comment]
LGTM

**Pull request closed without merging**
