### PR TITLE
[Team_Fantastic] feature：Added program entry file and learning documentation about vector

### PR DESCRIPTION
**Pull request by fanweiGit**
### What

- brief:  initial the program.
- author: Fantastic

### What changes are included in this PR?
Added program entry file and learning documentation about vector

### Are these changes tested?
yeah!

### CODE REVIEW

**Comment by Light-City** [comment]
1.Are these changes tested?
yeah!

yeah means ???


The directory structure is incorrect, you can refer to what others have done, or this document

https://github.com/datawhalechina/whale-starry/blob/main/stl/rules/pr.md

**Comment by fanweiGit** [comment]
### What
brief: initial the program.
author: Fantastic

### What changes are included in this PR?
Added program entry file and learning documentation about vector

### Are these changes tested?
image

**Comment by Light-City** [comment]
please fix conflict.

**Comment by Light-City** [comment]
your title style is wrong , reject.

**Pull request closed without merging**
