### PR TITLE
[fight_sw511_0] Feature: first Pr

### PR DESCRIPTION
**Pull request by Sw511**
### What

- brief: first pr test
- author: Sw511

### What changes are included in this PR?

包含了一个团队目录、个人目录、个人学习内容

### Are these changes tested?
Yes
image

### CODE REVIEW

**Comment by Light-City** [comment]
your code should follow google c++ style, such as:


```
int main () {
   ...
}
```

**Comment by Light-City** [comment]
Are these changes tested?

this answer doesn't quite match

**Comment by Light-City** [comment]
your title  style is wrong, see other.

**Comment by Sw511** [comment]
## What
brief: first pr test
author: Sw511
## What changes are included in this PR?
包含了一个团队目录、个人目录、个人学习内容

## Are these changes tested?
Yes

**Comment by martinx** [comment]
1: Delete.DS_Store, although it is added to .gitignore, the existing files are not deleted
2: The name of the team and user use lowercase, not uppercase.

```
Sw511
```

=> 

```
sw511
```

**Pull request closed without merging**
