### PR TITLE
[stay_hungry_0] Hello World pr

### PR DESCRIPTION
**Pull request by Killing11L**
### What?
- brief: 首次提交hello world测试pr
- author: feiwei

### What changes are included in this PR?
- 包含了一个团队目录、个人目录、个人学习内容。

### Are these changes tested?
- 提交首个测试程序main.cpp

### CODE REVIEW

**Comment by Light-City** [comment]
1.Please post a screenshot of the main program running on your computer and let me know that your machine can run C++ programs.
2.use markdown format your pr contents.

**Comment by Light-City** [comment]
> > 1.Please post a screenshot of the main program running on your computer and let me know that your machine can run C++ programs. 2.use markdown format your pr contents.
> 
> image Ok, I have modified it as requested.

sorray, did not see the directory modification

**Comment by Killing11L** [comment]
> > > 1.Please post a screenshot of the main program running on your computer and let me know that your machine can run C++ programs. 2.use markdown format your pr contents.
> > 
> > 
> > image Ok, I have modified it as requested.
> 
> sorray, did not see the directory modification

Sorry for the misunderstanding before, and I have revised and submitted it again.

**Comment by Light-City** [comment]
LGTM

**Pull request closed without merging**
